### ISSUE TITLE
nfsen-ng: 400 - Bad Request. Not enough parameters

### ISSUE THREAD

**Issue by vantage255** [mbolli/nfsen-ng#25]
When I make the API request: 
http://Flowserver/nfsen-ng/api/graph?datestart=1558137600&dateend=1558191175&type=flows&sources[0]=Router.1&sources[1]=Router.2&protocols[0]=tcp&ports[0]=80

I get the reply 
400 - Bad Request. Not enough parameters
in my browser and
nfsen-ng: 400 - Bad Request. Not enough parameters
in the syslog (With DEBUG logging level.

This would appear to be the proper format based on the doc.
What parameter am I missing here?

**Comment by Dona21** [comment]
Hi,

Thanks for pointing out this issue. You're getting a bad result because this part of the `README` has not been updated to match the full list of requested parameters for `/api/graph`

This api call requires an additional parameter "`display`" which can have one of these values "`protocols`", "`sources`" or "`ports`". We will update the `README`as soon as possible.

In your particular case you should append "`&display=ports`" to the URL. Taking your example, the following should work :
`http://Flowserver/nfsen-ng/api/graph?datestart=1558137600&dateend=1558191175&type=flows&sources[0]=Router.1&protocols[0]=tcp&ports[0]=80&display=ports`

You will notice that I removed part of the URL "`&sources[1]=Router.2`" because only 1 source or "any" is supported when using the "ports" display. This is somehow prevented if you use the nfsen-ng front-end but it is not if you build your own URL manually.

**Comment by vantage255** [comment]
Thank you.
Its working great now.
