### ISSUE TITLE
settings.php

### ISSUE THREAD

**Issue by enkikun** [mbolli/nfsen-ng#28]
Didn't find proper documentation for settngs.php.
I'd like to fetch data from my nfcapd files. Which type of DB i should use?
What ports section stands for?

$nfsen_config = array(
    'general' => array(
        'ports' => array(
            80, 22, 53,
        ),
        'sources' => array(
            's1', 's2',
        ),
        'db' => 'RRD',
    ),

**Comment by Dona21** [comment]
Hi,

If you install nfsen-ng by following the documentation you should have a default configuration that uses RRD. At the moment, this is the only implementation available and you can leave the default values regarding the db.

The ports array contains a list of destination ports that are passed to nfdump in order to filter data in the nfcapd files and generate corresponding graphs. This is useful if you would like to monitor flows for specific ports like ssh, http, https or whatever. The ports graph can then be viewed by switching the display selector to "Ports" in the frontend
