### ISSUE TITLE
PHP Notice:  Undefined offset

### ISSUE THREAD

**Issue by tb2496** [mbolli/nfsen-ng#47]
Hi, I keep getting these when trying to import ports:

PHP Notice:  Undefined offset: 2 in /var/www/html/nfsen-ng/backend/common/import.php on line 283
PHP Notice:  Undefined offset: 1 in /var/www/html/nfsen-ng/backend/common/import.php on line 284

Also, under flows and statistics tabs output is always csv when i click process data, regardless which output type is choosen.  unless I misunderstood how to show data there.

I'm using ubuntu 19.10 with php7.3

**Comment by cwscott** [comment]
I am seeing this as well. Using CentoOS 7.3 with PHP 7.2

# ./backend/cli.php -f -p -ps import
2020-05-05 18:57:15 CLI: Starting import
Resetting existing data...

Processing 4 sources...         0.0% 0/4388 ETC: ???. Elapsed: < 1 sec [>                              ]
Processing source c07-asr9k-01 (1/4)...
Scanning /var/nfdump...25.0% 1097/4388 ETC: < 1 sec. Elapsed: < 1 sec [=======>                       ]P                                       HP Notice:  Undefined offset: 2 in /var/www/html/nfsen-ng/backend/common/import.php on line 283
PHP Notice:  Undefined offset: 1 in /var/www/html/nfsen-ng/backend/common/import.php on line 284
PHP Notice:  Undefined offset: 2 in /var/www/html/nfsen-ng/backend/common/import.php on line 283
PHP Notice:  Undefined offset: 1 in /var/www/html/nfsen-ng/backend/common/import.php on line 284
PHP Notice:  Undefined offset: 2 in /var/www/html/nfsen-ng/backend/common/import.php on line 283
PHP Notice:  Undefined offset: 1 in /var/www/html/nfsen-ng/backend/common/import.php on line 284
PHP Notice:  Undefined offset: 2 in /var/www/html/nfsen-ng/backend/common/import.php on line 283
PHP Notice:  Undefined offset: 1 in /var/www/html/nfsen-ng/backend/common/import.php on line 284

**Comment by Dona21** [comment]
thanks @tb2496 and @cwscott  for reporting it.

I think this commit fbc626a58a2b5eb8ce86a2b8e1f5cd9a62832aff introduced the error. By commenting what has been added to nfdump.php (which has moved since then to nfsen-ng/backend/processor/) I got rid of these errors on my test server and the ports data (graph) are showing again.

Hi @nrensen, the summary lines are used to populate the ports datasources (used in the graph -> display -> ports). I would like to revert the changes from the referenced commit above. What impact would that have for you ? As you commited some other stuff, may I ask you directly (rather than checking all commits since that one) if that will cause an issue to anything else you commit ?

**Comment by nrensen** [comment]
I'm sure I can work around that if necessary. However another way to resolve that may be to accumulate the totals across all protocols in the foreach loop immediately preceding the summary processing in import.php, and not bothering with the summary at all.

**Comment by mbolli** [comment]
@nrensen good suggestion, thanks. @tb2496 and @cwscott this should be fixed!

**Comment by tb2496** [comment]
its working now, thanks. regarding flows and statistics I'm not seeing source or destination port, no matter which output type I choose.  is that by design?

**Comment by mbolli** [comment]
thanks for the feedback!
